//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatasetWriter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatasetWriter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;@DatasetName&quot;,
        ///  &quot;defaultMode&quot;: &quot;Push&quot;,
        ///  &quot;tables&quot;: [ { 
        ///      &quot;name&quot;: &quot;Contributions&quot;,
        ///      &quot;columns&quot;: [
        ///        { &quot;name&quot;: &quot;ContributionID&quot;, &quot;dataType&quot;: &quot;Int64&quot; },
        ///        { &quot;name&quot;: &quot;Contributor&quot;, &quot;dataType&quot;: &quot;string&quot; },
        ///        { &quot;name&quot;: &quot;State&quot;, &quot;dataType&quot;: &quot;string&quot;, &quot;dataCategory&quot;: &quot;StateOrProvince&quot; },
        ///        { &quot;name&quot;: &quot;City&quot;, &quot;dataType&quot;: &quot;string&quot;, &quot;dataCategory&quot;: &quot;Place&quot; },
        ///        { &quot;name&quot;: &quot;Zipcode&quot;, &quot;dataType&quot;: &quot;Int64&quot;, &quot;dataCategory&quot;: &quot;PostalCode&quot; },
        ///        { &quot;name&quot;: &quot;Gen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CampaignContributions_json {
            get {
                return ResourceManager.GetString("CampaignContributions_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CampaignContributionsReport_pbix {
            get {
                object obj = ResourceManager.GetObject("CampaignContributionsReport_pbix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;SurveyResponses&quot;,
        ///  &quot;defaultMode&quot;: &quot;Push&quot;,
        ///  &quot;tables&quot;: [ {
        ///      &quot;name&quot;: &quot;Surveys&quot;,
        ///      &quot;columns&quot;: [
        ///        { &quot;name&quot;: &quot;Attendee&quot;, &quot;dataType&quot;: &quot;string&quot; },
        ///        { &quot;name&quot;: &quot;DevYears&quot;, &quot;dataType&quot;: &quot;Double&quot; }
        ///      ]
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string SurveyResponses_json {
            get {
                return ResourceManager.GetString("SurveyResponses_json", resourceCulture);
            }
        }
    }
}
